SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/CondominiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class CondominiosController : Controller
    {
        //
        // GET: /Condominios/

        public ActionResult CrearCondominio()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearViviendas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearEspacios()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearSA()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        [HttpPost]
        public JsonResult GetRegiones(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetRegiones();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }


        [HttpPost]
        public JsonResult GetCondominios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetCondominios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetViviendas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendas();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public JsonResult GetEspacios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetEspacios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetComunas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();                
                var model = cond.GetComunas(int.Parse(collection["Region"]));
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearCondominio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                CONDOMINIO nuevo = new CONDOMINIO();
                nuevo.ID_COMUNA = int.Parse(collection["comuna"].ToString());
                nuevo.NOMBRE = collection["nombre"].ToString();
                nuevo.DIRECCION = collection["direccion"].ToString();
                string num = collection["numerodire"].ToString();
                nuevo.NUMERO_DIRECCION = int.Parse(num);
                nuevo.TELEFONO = int.Parse(collection["fono"].ToString());

                var model = cond.InsertarCondominio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearVivienda(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                VIVIENDA nuevo = new VIVIENDA();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_CALLE = collection["direccion"].ToString();
                nuevo.NUMERO = collection["numerodire"].ToString();
                nuevo.PLANTA_UBICACION = collection["planta"].ToString();

                var model = cond.InsertarVivienda(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        public JsonResult CrearEspacio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                ESPACIOS_COMUNES nuevo = new ESPACIOS_COMUNES();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_ESPACIO = collection["nombre"].ToString();
                nuevo.DESCRIPCION_ESPACIO = collection["descripcion"].ToString();

                var model = cond.InsertarEspacio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        [HttpPost]
        public JsonResult ObtenerResidenciasPorCondominio(FormCollection collection)
        {
            try
            {
                int condominio = int.Parse(collection["Condominio"].ToString());
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendasPorCondominio(condominio);
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult ObtenerInfoCondominiosPorUsuario(FormCollection collection)
        {
            try
            {

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/ResidentesController.cs
using SigescoDAL;
using SigescoDAL.Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sigesco.Controllers
{
    public class ResidentesController : Controller
    {
        //
        // GET: /Residentes/

        public ActionResult VerResidentesDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerResidentesAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerResidentesCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult RegistrarResidentesDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult RegistrarResidentesAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult ResidentesMorososDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult ResidentesMorososCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult ResidentesMorososAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }



        [HttpPost]
        public JsonResult ObtenerInfoResidentes(FormCollection collection)
        {
            int condominio = int.Parse(collection["Condominio"].ToString());
            ResidenteDAL dal = new ResidenteDAL();
            var model = dal.ObtenerInfoResidentePorCondominio(condominio);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CrearResidente(FormCollection collection)
        {
            PERSONA persona = new PERSONA();
            USUARIO usuario = new USUARIO();
            RESIDENTE residente = new RESIDENTE();
            USUARIO_X_CONDOMINIO uxc = new USUARIO_X_CONDOMINIO();
            var _rut = collection["Rut"].ToString().Split('-');
            persona.RUT = int.Parse(_rut[0]);
            persona.PRIMER_NOMBRE=collection["PrimerNom"].ToString();
            persona.SEGUNDO_NOMBRE = collection["SegNom"].ToString();
            persona.APELLIDO_PATERNO = collection["ApePat"].ToString();
            persona.APELLIDO_MATERNO = collection["ApeMat"].ToString();
            persona.FECHA_NACIMIENTO = Convert.ToDateTime(collection["Fecha"].ToString());
            string fono = collection["Fono"].ToString();
            if (fono == "")
            { persona.TELEFONO = null; }
            else
            { persona.TELEFONO = int.Parse(fono);}           
            persona.CORREO = collection["Email"].ToString();
            persona.SEXO = collection["Sexo"].ToString();
            usuario.ID_USUARIO = int.Parse('1' + _rut[0]);
            usuario.ID_TIPO_USUARIO = 1;
            usuario.RUT = int.Parse(_rut[0]);
            usuario.CLAVE=collection["Pass"].ToString();
            residente.ID_RESIDENTE = int.Parse(collection["Residencia"].ToString() + _rut[0]);
            residente.RUT = int.Parse(_rut[0]);
            residente.ID_VIVIENDA = int.Parse(collection["Residencia"].ToString());
            residente.FECHA_INGRESO = DateTime.Now;
            uxc.ID_USUARIO = usuario.ID_USUARIO;
            uxc.ID_CONDOMINIO = int.Parse(collection["Condominio"].ToString());
            uxc.ID_UXC = int.Parse(usuario.ID_USUARIO+collection["Condominio"].ToString());
            ResidenteDAL dal = new ResidenteDAL();
            var model = dal.AgregarPersonaUsuarioResidente(persona,usuario,residente,uxc);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }
        

        [HttpPost]
        public JsonResult AsignarResidente(FormCollection collection)
        {
            RESIDENTE residente = new RESIDENTE();
            string _rut = collection["Persona"].ToString();
            residente.ID_RESIDENTE = int.Parse(collection["Residencia"].ToString() + _rut);
            residente.RUT = int.Parse(_rut);
            residente.ID_VIVIENDA = int.Parse(collection["Residencia"].ToString());
            residente.FECHA_INGRESO = DateTime.Now;
            ResidenteDAL dal = new ResidenteDAL();
            var model = dal.AgregarResidente(residente);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

    }//fin clase
}

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Residentes/VerResidentesAdm.cshtml
@{
    ViewBag.Title = "Ver Residentes";
    Layout = "~/Views/Compartida/_PaginaDiseño5.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
        </h2>
    </div>
    <div class="row">
        <h3>
            <strong>VER RESIDENTES</strong>
        </h3>
        <hr />
    </div>
    <div class="row" id="tabla_reserv">
        <div class="col-lg-12">
            <form class="form-inline well">
                <label for="selectCondominio">Condominio</label>
                <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio">
                    <option value="">Seleccione</option>
                </select>
                <button type="button" class="btn btn-primary" onclick="filtarCondominios()">Ver información disponible</button>
            </form>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading">
                    Información de  Residentes
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" id="panelTabla">
                    <div class="alert alert-success" style="overflow-x: auto;">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
                            <thead>
                                <tr>
                                    <th>Domicilio</th>
                                    <th>Nombre</th>
                                    <th>Rut</th>
                                    <th>Usuario</th>
                                    <th>Correo</th>
                                    <th>Telefono</th>
                                </tr>
                            </thead>
                            <tbody id="cuerpo"></tbody>
                        </table>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <div id="dialogoverlay"></div>
        <div id="dialogbox">
            <div>
                <div id="dialogboxhead"></div>
                <div id="dialogboxbody"></div>
                <div id="dialogboxfoot"></div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        $("#panelTabla").hide();
        cargarMisCondominios();

    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener condominios por usuario"');
            }
        });
    }

  function filtarCondominios() {
        $("#panelTabla").hide();
        var condominio = $('select#selectCondominio').val();

        if(condominio=="")
        {
            Alert.render('Debe seleccionar un condominio de residencia');
        }else
        {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ObtenerInfoResidentes", "Residentes")',
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: { "Condominio": condominio },
                success: function (respuesta) {
                    $("#cuerpo").empty();
                    if (respuesta.model != "") {
                        var filas = respuesta.model.length;
                        for (i = 0 ; i < filas; i++) {
                            var fila = respuesta.model[i];
                            var celda = fila.toString().split(";");
                            var nuevafila = "<tr>" +
                                "<td>" + celda[0] + "</td>" +
                                "<td>" + celda[1] + "</td>" +
                                "<td>" + celda[2] + "</td>" +
                                "<td>" + celda[5] + "</td>" +
                                "<td>" + celda[3] + "</td>" +
                                "<td>" + celda[4] + "</td></tr>"

                            $("#cuerpo").append(nuevafila);
                        }
                        $("#panelTabla").show();
                    } else {
                        Alert.render('No se han encontrado información para el condominio');
                    }

                },
                error: function (xhr, textStatus, errorThrown) {
                    Alert.render('Error: No se pudo cargar método "Obtener Residentes"');
                }
            });
        }
  }


</script>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Residentes/VerResidentesCons.cshtml
@{
    ViewBag.Title = "Ver Residentes";
    Layout = "~/Views/Compartida/_PaginaDiseño4.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
        </h2>
    </div>
    <div class="row">
        <h3>
            <strong>VER RESIDENTES</strong>
        </h3>
        <hr />
    </div>
    <div class="row" id="tabla_reserv">
        <div class="col-lg-12">
            <form class="form-inline well">
                <label for="selectCondominio">Condominio</label>
                <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio">
                    <option value="">Seleccione</option>
                </select>
                <button type="button" class="btn btn-primary" onclick="filtarCondominios()">Ver información disponible</button>
            </form>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading">
                    Información de  Residentes
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" id="panelTabla">
                    <div class="alert alert-success" style="overflow-x: auto;">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
                            <thead>
                                <tr>
                                    <th>Domicilio</th>
                                    <th>Nombre</th>
                                    <th>Rut</th>
                                    <th>Usuario</th>
                                    <th>Correo</th>
                                    <th>Telefono</th>
                                </tr>
                            </thead>
                            <tbody id="cuerpo"></tbody>
                        </table>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <div id="dialogoverlay"></div>
        <div id="dialogbox">
            <div>
                <div id="dialogboxhead"></div>
                <div id="dialogboxbody"></div>
                <div id="dialogboxfoot"></div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        $("#panelTabla").hide();
        cargarMisCondominios();

    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener condominios por usuario"');
            }
        });
    }

  function filtarCondominios() {
        $("#panelTabla").hide();
        var condominio = $('select#selectCondominio').val();

        if(condominio=="")
        {
            Alert.render('Debe seleccionar un condominio de residencia');
        }else
        {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ObtenerInfoResidentes", "Residentes")',
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: { "Condominio": condominio },
                success: function (respuesta) {
                    $("#cuerpo").empty();
                    if (respuesta.model != "") {
                        var filas = respuesta.model.length;
                        for (i = 0 ; i < filas; i++) {
                            var fila = respuesta.model[i];
                            var celda = fila.toString().split(";");
                            var nuevafila = "<tr>" +
                                "<td>" + celda[0] + "</td>" +
                                "<td>" + celda[1] + "</td>" +
                                "<td>" + celda[2] + "</td>" +
                                "<td>" + celda[5] + "</td>" +
                                "<td>" + celda[3] + "</td>" +
                                "<td>" + celda[4] + "</td></tr>"

                            $("#cuerpo").append(nuevafila);
                        }
                        $("#panelTabla").show();
                    } else {
                        Alert.render('No se han encontrado información para el condominio');
                    }

                },
                error: function (xhr, textStatus, errorThrown) {
                    Alert.render('Error: No se pudo cargar método "Obtener Residentes"');
                }
            });
        }
  }


</script>