SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/AreasComunesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class AreasComunesController : Controller
    {
        //
        // GET: /AreasComunes/

        public ActionResult VerAreas()
        {            
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
            
        }

        public ActionResult VerAreasDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }

        }

        public ActionResult VerAreasCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }

        }

        public ActionResult VerAreasAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }

        }

        public ActionResult VerReservasDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }

        }

        public ActionResult VerReservasCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }

        }

        public ActionResult VerReservasAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }

        }

        public ActionResult AdmAreas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }


        [HttpPost]
        public JsonResult ObtenerEspaciosPorCondominio(FormCollection collection)
        {
            try
            {
                int condominio = int.Parse(collection["Condominio"].ToString());
                AreasComunesDAL area = new AreasComunesDAL();
                var model = area.GetAreasPorCondominio(condominio);
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }
}

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/CondominiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class CondominiosController : Controller
    {
        //
        // GET: /Condominios/

        public ActionResult CrearCondominio()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearViviendas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearEspacios()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearSA()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        [HttpPost]
        public JsonResult GetRegiones(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetRegiones();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }


        [HttpPost]
        public JsonResult GetCondominios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetCondominios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetViviendas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendas();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public JsonResult GetEspacios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetEspacios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetComunas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();                
                var model = cond.GetComunas(int.Parse(collection["Region"]));
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearCondominio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                CONDOMINIO nuevo = new CONDOMINIO();
                nuevo.ID_COMUNA = int.Parse(collection["comuna"].ToString());
                nuevo.NOMBRE = collection["nombre"].ToString();
                nuevo.DIRECCION = collection["direccion"].ToString();
                string num = collection["numerodire"].ToString();
                nuevo.NUMERO_DIRECCION = int.Parse(num);
                nuevo.TELEFONO = int.Parse(collection["fono"].ToString());

                var model = cond.InsertarCondominio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearVivienda(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                VIVIENDA nuevo = new VIVIENDA();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_CALLE = collection["direccion"].ToString();
                nuevo.NUMERO = collection["numerodire"].ToString();
                nuevo.PLANTA_UBICACION = collection["planta"].ToString();

                var model = cond.InsertarVivienda(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        public JsonResult CrearEspacio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                ESPACIOS_COMUNES nuevo = new ESPACIOS_COMUNES();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_ESPACIO = collection["nombre"].ToString();
                nuevo.DESCRIPCION_ESPACIO = collection["descripcion"].ToString();

                var model = cond.InsertarEspacio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        [HttpPost]
        public JsonResult ObtenerResidenciasPorCondominio(FormCollection collection)
        {
            try
            {
                int condominio = int.Parse(collection["Condominio"].ToString());
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendasPorCondominio(condominio);
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult ObtenerInfoCondominiosPorUsuario(FormCollection collection)
        {
            try
            {

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/AreasComunes/AdmAreas.cshtml
@{
    ViewBag.Title = "AdmAreas";
    Layout = "~/Views/Compartida/_PaginaDiseño2.cshtml";
}

<h2>AdmAreas</h2>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/AreasComunes/VerAreas.cshtml
@{
    ViewBag.Title = "Ver Areas";
    Layout = "~/Views/Compartida/_PaginaDiseño2.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
        </h2>
    </div>
    <div class="row">
        <h3>
            <strong>AREAS/ESPACIOS COMUNES</strong> 
        </h3>
    </div>
    <div class="row" id="tabla_reserv">
        <div class="col-lg-12">
            <form class="form-inline">
                <label for="selectCondominio">Condominio</label>
                <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio">
                    <option value="">Seleccione</option>
                </select>
                <button type="button" class="btn btn-primary" onclick="filtarEspacios()">Ver información disponible</button>
            </form>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading">
                    Información de  Áreas o Espacios Comunes
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" id="panelTabla">
                    <div class="alert alert-success" style="overflow-x: auto;">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
                            <thead>
                                <tr>
                                    <th>Nombre de Espacio</th>
                                    <th>Descripción de Espacio</th>
                                </tr>
                            </thead>
                            <tbody id="cuerpo"></tbody>
                        </table>
                        <!-- /.table-responsive -->
                        </div>
                    </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->
<div id="dialogoverlay"></div>
<div id="dialogbox">
    <div>
        <div id="dialogboxhead"></div>
        <div id="dialogboxbody"></div>
        <div id="dialogboxfoot"></div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        $("#panelTabla").hide();
        cargarMisCondominios();
        
    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener condominios por usuario"');
            }
        });
    }

    function filtarEspacios() {
        $("#panelTabla").hide();
        var condominio = $('select#selectCondominio').val();

        if(condominio=="")
        {
            Alert.render('Debe seleccionar un condominio de residencia');
        }else
        {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ObtenerEspaciosPorCondominio", "AreasComunes")',
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: { "Condominio": condominio },
                success: function (respuesta) {
                    $("#cuerpo").empty();
                    if (respuesta.model != "") {
                        var filas = respuesta.model.length;
                        for (i = 0 ; i < filas; i++) {
                            var fila = respuesta.model[i];
                            var celda = fila.toString().split(";");
                            var nuevafila = "<tr>" +
                                "<td>" + celda[1] + "</td>" +
                                "<td>" + celda[2] + "</td></tr>"

                            $("#cuerpo").append(nuevafila);
                        }
                    } else {
                        Alert.render('No se han encontrado información para su condominio');
                    }
                    $("#panelTabla").show();
                },
                error: function (xhr, textStatus, errorThrown) {
                    Alert.render('Error: No se pudo cargar método "Obtener Areas"');
                }
            });
        }
    }

</script>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/AreasComunes/VerAreasAdm.cshtml
@{
    ViewBag.Title = "Ver Areas";
    Layout = "~/Views/Compartida/_PaginaDiseño5.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
        </h2>
    </div>
    <div class="row">
        <h3>
            <strong>AREAS/ESPACIOS COMUNES</strong>
        </h3>
        <hr />
    </div>
    <div class="row" id="tabla_reserv">
        <div class="col-lg-12">
            <form class="form-inline well">
                <label for="selectCondominio">Condominio</label>
                <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio">
                    <option value="">Seleccione</option>
                </select>
                <button type="button" class="btn btn-primary" onclick="filtarEspacios()">Ver información disponible</button>
            </form>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading">
                    Información de  Áreas o Espacios Comunes
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" id="panelTabla">
                    <div class="alert alert-success" style="overflow-x: auto;">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
                            <thead>
                                <tr>
                                    <th>Nombre de Espacio</th>
                                    <th>Descripción de Espacio</th>
                                </tr>
                            </thead>
                            <tbody id="cuerpo"></tbody>
                        </table>
                        <!-- /.table-responsive -->
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->
<div id="dialogoverlay"></div>
<div id="dialogbox">
    <div>
        <div id="dialogboxhead"></div>
        <div id="dialogboxbody"></div>
        <div id="dialogboxfoot"></div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        $("#panelTabla").hide();
        cargarMisCondominios();

    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener condominios por usuario"');
            }
        });
    }

    function filtarEspacios() {
        $("#panelTabla").hide();
        var condominio = $('select#selectCondominio').val();

        if(condominio=="")
        {
            Alert.render('Debe seleccionar un condominio de residencia');
        }else
        {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ObtenerEspaciosPorCondominio", "AreasComunes")',
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: { "Condominio": condominio },
                success: function (respuesta) {
                    $("#cuerpo").empty();
                    if (respuesta.model != "") {
                        var filas = respuesta.model.length;
                        for (i = 0 ; i < filas; i++) {
                            var fila = respuesta.model[i];
                            var celda = fila.toString().split(";");
                            var nuevafila = "<tr>" +
                                "<td>" + celda[1] + "</td>" +
                                "<td>" + celda[2] + "</td></tr>"

                            $("#cuerpo").append(nuevafila);
                        }
                    } else {
                        Alert.render('No se han encontrado información para su condominio');
                    }
                    $("#panelTabla").show();
                },
                error: function (xhr, textStatus, errorThrown) {
                    Alert.render('Error: No se pudo cargar método "Obtener Areas"');
                }
            });
        }
    }

</script>