SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/CondominiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class CondominiosController : Controller
    {
        //
        // GET: /Condominios/

        public ActionResult CrearCondominio()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearViviendas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearEspacios()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearSA()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        [HttpPost]
        public JsonResult GetRegiones(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetRegiones();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }


        [HttpPost]
        public JsonResult GetCondominios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetCondominios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetViviendas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendas();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public JsonResult GetEspacios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetEspacios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetComunas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();                
                var model = cond.GetComunas(int.Parse(collection["Region"]));
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearCondominio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                CONDOMINIO nuevo = new CONDOMINIO();
                nuevo.ID_COMUNA = int.Parse(collection["comuna"].ToString());
                nuevo.NOMBRE = collection["nombre"].ToString();
                nuevo.DIRECCION = collection["direccion"].ToString();
                string num = collection["numerodire"].ToString();
                nuevo.NUMERO_DIRECCION = int.Parse(num);
                nuevo.TELEFONO = int.Parse(collection["fono"].ToString());

                var model = cond.InsertarCondominio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearVivienda(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                VIVIENDA nuevo = new VIVIENDA();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_CALLE = collection["direccion"].ToString();
                nuevo.NUMERO = collection["numerodire"].ToString();
                nuevo.PLANTA_UBICACION = collection["planta"].ToString();

                var model = cond.InsertarVivienda(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        public JsonResult CrearEspacio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                ESPACIOS_COMUNES nuevo = new ESPACIOS_COMUNES();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_ESPACIO = collection["nombre"].ToString();
                nuevo.DESCRIPCION_ESPACIO = collection["descripcion"].ToString();

                var model = cond.InsertarEspacio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        [HttpPost]
        public JsonResult ObtenerResidenciasPorCondominio(FormCollection collection)
        {
            try
            {
                int condominio = int.Parse(collection["Condominio"].ToString());
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendasPorCondominio(condominio);
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult ObtenerInfoCondominiosPorUsuario(FormCollection collection)
        {
            try
            {

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/MultasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class MultasController : Controller
    {
        //
        // GET: /Multas/

        public ActionResult VerMultas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerPagos()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult AdmMultas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult IngresarMultasDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerPagosMultasDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerPagosMultasCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerPagosMultasAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerPagosMultasResidenteCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerPagosMultasResidenteAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        [HttpPost]
        public JsonResult ObtenerMultasPorVivienda(FormCollection collection)
        {
            GastosDAL bd = new GastosDAL();
            int vivienda = int.Parse(collection["Vivienda"].ToString());
            var model = bd.ObtenerVistaMultasPorVivienda(vivienda);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public JsonResult IngresarMulta(FormCollection collection)
        {
            GastosDAL bd = new GastosDAL();
            GASTO multa = new GASTO();
            multa.NOMBRE_GASTO = "Multa";
            multa.FECHA_GASTO = DateTime.Now;
            multa.ID_TIPO_GASTO = 4;
            multa.ESTADO = "NO PAGADO";
            multa.ID_VIVIENDA = int.Parse(collection["Vivienda"].ToString());
            multa.DESCRIPCION = collection["Descipcion"].ToString();
            multa.MONTO_GASTO = int.Parse(collection["Monto"].ToString());
            var model = bd.IngresarNuevaMulta(multa);
            if (model)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ObtenerInfoMultaPagadaPorFechaPorCondominio(FormCollection collection)
        {
            GastosDAL bd = new GastosDAL();
            string fecha = collection["Hasta"].ToString();
            DateTime desde = Convert.ToDateTime(collection["Desde"].ToString());
            DateTime hasta = Convert.ToDateTime(fecha + " 23:59:00");
            int condominio = int.Parse(collection["Condominio"].ToString());
            var model = bd.ObtenerVistaMultasPagaPorCondominioPorFecha(condominio,desde,hasta);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public JsonResult ObtenerInfoMultaNoPagadaPorFechaPorCondominio(FormCollection collection)
        {
            GastosDAL bd = new GastosDAL();
            string fecha = collection["Hasta"].ToString();
            DateTime desde = Convert.ToDateTime(collection["Desde"].ToString());
            DateTime hasta = Convert.ToDateTime(fecha + " 23:59:00");
            int condominio = int.Parse(collection["Condominio"].ToString());
            var model = bd.ObtenerVistaMultasNoPagaPorCondominioPorFecha(condominio, desde, hasta);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }


    }//fin clase
}

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Multas/AdmMultas.cshtml
@{
    ViewBag.Title = "AdmMultas";
    Layout = "~/Views/Compartida/_PaginaDiseño2.cshtml";
}

<h2>AdmMultas</h2>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Multas/IngresarMultasDir.cshtml
@{
    ViewBag.Title = "Ingresar Multas";
    Layout = "~/Views/Compartida/_PaginaDiseño3.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
        </h2>
    </div>
    <!-- /.row -->
    <div class="row">
        <h3>
            <strong>INGRESAR MULTAS</strong>
        </h3>
        <hr />
    </div>
        <div class="panel panel-danger">
            <div class="panel-heading">
                <p class="help-block">Las multas se asocian a las residencias</p>
                <form class="form-inline">
                    <label for="selectCondominio">Condominio</label>
                    <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio" onchange="filtrarViviendas()"></select>
                    <label for="selectResidencia1">Residencias</label>
                    <select class="form-control" name="selectResidencia1" id="selectResidencia1">
                        <option value="">Seleccione</option>
                    </select>
                </form>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="nuevaMulta" class="alert alert-danger">
                    <div class="form-group">
                        <label>Motivo de la Multa</label>**
                        <textarea type="text" id="txtMotivo" style="min-height:50px" class="form-control" maxlength="100" placeholder="..máximo 100 caracteres.."></textarea>                        
                        <label>Monto a Cancelar</label>**
                        <input type="number" id="txtMonto" class="form-control" min="1" placeholder="..cifra a cobrar">
                        <br />
                        <p class="help-block">La fecha de emición se guarda automáticamente al momento de registrar la multa</p>
                    </div>   
                    <button type="button" class="btn btn-danger" onclick="ingresarMulta()">Ingresar Multa</button>
                </div>
            </div>
            <!-- .panel-body -->
        </div>
        <!-- /.panel -->
</div>
<!-- /.container-fluid -->
<div id="dialogoverlay"></div>
<div id="dialogbox">
    <div>
        <div id="dialogboxhead"></div>
        <div id="dialogboxbody"></div>
        <div id="dialogboxfoot"></div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        cargarMisCondominios();
    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener viviendas por usuario"');
            }
        });
    }

    function filtrarViviendas() {
        var condominio = $('select#selectCondominio').val();
        if (condominio == "") {
            Alert.render('Debe indicar un condominio');
        } else {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ObtenerResidenciasPorCondominio", "Condominios")',
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: { "Condominio": condominio },
                success: function (respuesta) {
                    if (respuesta.model != "") {
                        $("#selectResidencia1").empty()
                        var filas = respuesta.model.length;
                        $("#selectResidencia1").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                        for (i = 0 ; i < filas; i++) {
                            var fila = respuesta.model[i];
                            var celda = fila.toString().split(";");
                            var nuevafila =
                                "<option value=" + celda[0] + ">" + celda[1] + ' #' + celda[2] + ' - Piso/Panta ' + celda[3] + "</option>"
                            $("#selectResidencia1").append(nuevafila)
                        }
                    } else {
                        Alert.render('No se han encontrado viviendas para este condominio');
                        $("#selectResidencia1").empty()
                        $("#selectResidencia1").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    Alert.render('Error: No se pudo cargar método "Obtener viviendas por condominios"');
                }
            });
        }
    }


    function ingresarMulta()
    {
        var vivienda = $('select#selectResidencia1').val();
        var descricion = $('#txtMotivo').val();
        var monto = $('#txtMonto').val();

        if(vivienda=="")
        {
            Alert.render('Debe determinar una vivienda a multar');
        } else {
            if(descricion.length<6)
            {
                Alert.render('Debe indicar un motivo por generar la multa');
            } else {
                if(monto==0)
                {
                    Alert.render('Debe indicar un monto por generar la multa');
                }
                else {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("IngresarMulta", "Multas")',
                        content: "application/json; charset=utf-8",
                        dataType: "json",
                        data: { "Vivienda":vivienda,"Descipcion":descricion,"Monto":monto},
                        success: function (respuesta) {
                            if (respuesta.model != "") {
                                
                                Alert.render('Multa ingresada correctamente');
                                $('#txtMotivo').val("");
                                $('#txtMonto').val("");
                                
                            } else {
                                Alert.render('No se han conseguido ingresar la multa');
                            }
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            Alert.render('Error: No se pudo cargar método "Obtener viviendas por condominios"');
                        }
                    });
                }
            }
        }
    }
   

</script>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Multas/VerPagos.cshtml
@{
    ViewBag.Title = "VerPagos";
    Layout = "~/Views/Compartida/_PaginaDiseño2.cshtml";
}

<h2>VerPagos</h2>