SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class AnunciosController : Controller
    {
        //
        // GET: /Anuncios/

        public ActionResult VerAnuncios()
        {
            if (Session["UserName"] != null)
            {                
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerLibroCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult AgregarEventoCons()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerLibroAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult AgregarEventoAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerAnunciosDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearAnunciosDir()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult VerAnunciosAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearAnunciosAdm()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult AdmAnuncios()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }


        [HttpPost]
        public JsonResult Listar20Ultimos(FormCollection collection)
        {
            AnunciosDAL bd = new AnunciosDAL();
            int condominio = int.Parse(collection["Condominio"].ToString());
            var model = bd.Obtener20UltimosAuncios(condominio);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public JsonResult ListarLibro(FormCollection collection)
        {
            AnunciosDAL bd = new AnunciosDAL();
            int condominio = int.Parse(collection["Condominio"].ToString());
            var model = bd.ListarLibro(condominio);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public JsonResult GrabarLibro(FormCollection collection)
        {
            AnunciosDAL bd = new AnunciosDAL();
            LIBRO_SUCESOS libro = new LIBRO_SUCESOS();
            libro.ID_CONDOMINIO = int.Parse(collection["Condominio"].ToString());
            libro.REFERENCIA = (collection["Persona"].ToString()+" - "+collection["Perfil"].ToString());
            libro.DETALLES = collection["Cuerpo"].ToString();
            libro.FECHA_SUCESO = DateTime.Now;
            var model = bd.GrabarLibro(libro);
            if (model != null)
            {
                var result = new { Success = true, Message = "Succes Message", model };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public JsonResult CrearAnuncios(FormCollection collection)
        {
            AnunciosDAL bd = new AnunciosDAL();
            ANUNCIOS anun = new ANUNCIOS();
            anun.ID_CONDOMINIO = int.Parse(collection["Condominio"].ToString());
            anun.TITULO = collection["Titulo"].ToString();
            anun.CUERPO = collection["Cuerpo"].ToString();
            anun.REMITENTE = collection["Remitente"].ToString();
            anun.FECHA_ANUNCIO = DateTime.Now;
            var model = bd.CrearAnuncio(anun);
            if (model)
            {
                var result = new { Success = true, Message = "Succes Message"};
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { Success = false, Message = "Error Message" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

    }//fin clase
}

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Controllers/CondominiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SigescoDAL;
using SigescoDAL.Modelo;
using SigescoDAL.Vistas;

namespace Sigesco.Controllers
{
    public class CondominiosController : Controller
    {
        //
        // GET: /Condominios/

        public ActionResult CrearCondominio()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearViviendas()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearEspacios()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        public ActionResult CrearSA()
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Inicio");
            }
        }

        [HttpPost]
        public JsonResult GetRegiones(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetRegiones();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }


        [HttpPost]
        public JsonResult GetCondominios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetCondominios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetViviendas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendas();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public JsonResult GetEspacios(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetEspacios();
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult GetComunas(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();                
                var model = cond.GetComunas(int.Parse(collection["Region"]));
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearCondominio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                CONDOMINIO nuevo = new CONDOMINIO();
                nuevo.ID_COMUNA = int.Parse(collection["comuna"].ToString());
                nuevo.NOMBRE = collection["nombre"].ToString();
                nuevo.DIRECCION = collection["direccion"].ToString();
                string num = collection["numerodire"].ToString();
                nuevo.NUMERO_DIRECCION = int.Parse(num);
                nuevo.TELEFONO = int.Parse(collection["fono"].ToString());

                var model = cond.InsertarCondominio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult CrearVivienda(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                VIVIENDA nuevo = new VIVIENDA();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_CALLE = collection["direccion"].ToString();
                nuevo.NUMERO = collection["numerodire"].ToString();
                nuevo.PLANTA_UBICACION = collection["planta"].ToString();

                var model = cond.InsertarVivienda(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        public JsonResult CrearEspacio(FormCollection collection)
        {
            try
            {
                CondominioDAL cond = new CondominioDAL();
                ESPACIOS_COMUNES nuevo = new ESPACIOS_COMUNES();
                nuevo.ID_CONDOMINIO = int.Parse(collection["condominio"].ToString());
                nuevo.NOMBRE_ESPACIO = collection["nombre"].ToString();
                nuevo.DESCRIPCION_ESPACIO = collection["descripcion"].ToString();

                var model = cond.InsertarEspacio(nuevo);
                if (model)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            
        }


        [HttpPost]
        public JsonResult ObtenerResidenciasPorCondominio(FormCollection collection)
        {
            try
            {
                int condominio = int.Parse(collection["Condominio"].ToString());
                CondominioDAL cond = new CondominioDAL();
                var model = cond.GetViviendasPorCondominio(condominio);
                if (model != null)
                {
                    var result = new { Success = true, Message = "Succes Message", model };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { Success = false, Message = "Error Message" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public JsonResult ObtenerInfoCondominiosPorUsuario(FormCollection collection)
        {
            try
            {

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Anuncios/AdmAnuncios.cshtml
@{
    ViewBag.Title = "AdmAnuncios";
    Layout = "~/Views/Compartida/_PaginaDiseño2.cshtml";
}

<h2>AdmAnuncios</h2>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Anuncios/AgregarEventoAdm.cshtml
@{
    ViewBag.Title = "Agregar Evento";
    Layout = "~/Views/Compartida/_PaginaDiseño5.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
            <input type="text" id="lb_perfil" hidden value="@Session["NomPerfil"].ToString()">
        </h2>
    </div>
    <!-- /.row -->
    <div class="row">
        <h3>
            <strong>LIBRO DE ACTAS</strong>
        </h3>
        <hr />
    </div>
    <div class="row">
        <div class="col-lg-12">
            <form class="form-inline">
                <label for="selectCondominio">Condominio</label>
                <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio">
                    <option value="">Seleccione</option>
                </select>
            </form>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        <h4>Libro de Actas</h4>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div id="panelBody" class="panel-body">
                    <div class="alert alert-default">
                        <span class="pull-right text-muted">
                            <em>La fecha se registrará al momento de ingresar el evento</em>
                        </span>
                        <br />
                        <h4>@Session["UserName"].ToString() - @Session["NomPerfil"].ToString()</h4>
                        <div class="form-group">
                            <textarea id="cuerpo" class="form-control" style="height:300px" maxlength="1000" placeholder="..tiene un maximo de 1000 caracteres para ingresar lo requerido"></textarea>
                        </div>

                    </div>
                    <input type="button" class="btn btn-primary" onclick="GrabarLibro()" value="Guardar Registro" />
                </div>
                <!-- .panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
</div>
<!-- /.container-fluid -->
<div id="dialogoverlay"></div>
<div id="dialogbox">
    <div>
        <div id="dialogboxhead"></div>
        <div id="dialogboxbody"></div>
        <div id="dialogboxfoot"></div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        cargarMisCondominios();
    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener condominios por usuario"');
            }
        });
    }

    function GrabarLibro() {

        var condominio = $('select#selectCondominio').val();
        var cuerpo = $("#cuerpo").val();
        var usuario = $("#lb_nombreu").val();
        var perfil = $("#lb_perfil").val();

        if (cuerpo.length < 10)
        {
            Alert.render('Debe agregar un cuerpo de al menos 10 caracteres');
        } else
        {
            if (condominio == "") {
                Alert.render('Debe seleccionar un condominio de residencia');
            } else {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GrabarLibro", "Anuncios")',
                    content: "application/json; charset=utf-8",
                    dataType: "json",
                    data: { "Condominio": condominio,"Perfil":perfil,"Persona":usuario,"Cuerpo":cuerpo },
                    success: function (respuesta) {
                        if (respuesta.model != "") {
                            Alert.render('Libro actualizado correctamente');
                            $("#cuerpo").val("");
                        } else {
                            Alert.render('No se han conseguido grabar el registro');
                        }
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        Alert.render('Error: No se pudo cargar método "Grabar Libro"');
                    }
                });
            }
        }

    }

</script>

SIGESCO/Proyecto SIGESCOv7/Sigesco/Sigesco/Views/Anuncios/AgregarEventoCons.cshtml
@{
    ViewBag.Title = "Agrega Evento";
    Layout = "~/Views/Compartida/_PaginaDiseño4.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h2>
            <input type="text" id="lb_nombreu" hidden value="@Session["UserName"].ToString()">
            <input type="text" id="lb_usuario" hidden value="@Session["UserID"].ToString()">
            <input type="text" id="lb_perfil" hidden value="@Session["NomPerfil"].ToString()">
        </h2>
    </div>
    <!-- /.row -->
    <div class="row">
        <h3>
            <strong>LIBRO DE ACTAS</strong>
        </h3>
        <hr />
    </div>
    <div class="row">
        <div class="col-lg-12">
            <form class="form-inline">
                <label for="selectCondominio">Condominio</label>
                <select style="width:250px" class="form-control" name="selectCondominio" id="selectCondominio">
                    <option value="">Seleccione</option>
                </select>                
            </form>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        <h4>Libro de Actas</h4>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div id="panelBody" class="panel-body">
                    <div class="alert alert-default">
                    <span class="pull-right text-muted">
                        <em>La fecha se registrará al momento de ingresar el evento</em>
                    </span>
                    <br/>
                    <h4>@Session["UserName"].ToString() - @Session["NomPerfil"].ToString()</h4>
                        <div class="form-group">
                            <textarea id="cuerpo"class="form-control" style="height:300px" maxlength="1000" placeholder="..tiene un maximo de 1000 caracteres para ingresar lo requerido"></textarea>    
                        </div>
                    
                    </div>
                    <input type="button" class="btn btn-primary" onclick="GrabarLibro()" value="Guardar Registro"/>
                </div>
                <!-- .panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
</div>
<!-- /.container-fluid -->
<div id="dialogoverlay"></div>
<div id="dialogbox">
    <div>
        <div id="dialogboxhead"></div>
        <div id="dialogboxbody"></div>
        <div id="dialogboxfoot"></div>
    </div>
</div>
<script src="~/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        cargarMisCondominios();
    });
    function CustomAlert() {
        this.render = function (dialog) {
            var winW = window.innerWidth;
            var winH = window.innerHeight;
            var dialogoverlay = document.getElementById('dialogoverlay');
            var dialogbox = document.getElementById('dialogbox');
            dialogoverlay.style.display = "block";
            dialogoverlay.style.height = winH + "px";
            dialogbox.style.left = (winW / 2) - (550 * .5) + "px";
            dialogbox.style.top = "100px";
            dialogbox.style.display = "block";
            document.getElementById('dialogboxhead').innerHTML = "Información";
            document.getElementById('dialogboxbody').innerHTML = dialog;
            document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">Entendido</button>';
        }
        this.ok = function () {
            document.getElementById('dialogbox').style.display = "none";
            document.getElementById('dialogoverlay').style.display = "none";
        }
    }
    var Alert = new CustomAlert();

    function cargarMisCondominios() {
        $("#panelReservar").hide();
        var usuario = $('#lb_usuario').val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ObtenerCondominiosPorUsuario", "Condominios")',
            content: "application/json; charset=utf-8",
            dataType: "json",
            data: { "Usuario": usuario },
            success: function (respuesta) {
                $("#botonReservar").hide();
                if (respuesta.model != "") {
                    $("#selectCondominio").hide()
                    $("#filtro").show();
                    $("#selectCondominio").empty()
                    var filas = respuesta.model.length;
                    $("#selectCondominio").append("<option value=" + '"' + '"' + ">Seleccione</option>")
                    for (i = 0 ; i < filas; i++) {
                        var fila = respuesta.model[i];
                        var celda = fila.toString().split(";");
                        var nuevafila =
                            "<option value=" + celda[0] + ">" + celda[1] + "</option>"
                        $("#selectCondominio").append(nuevafila)
                    }
                    $("#selectCondominio").show();
                } else {
                    Alert.render('No se han encontrado condominios para su usuario');
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                Alert.render('Error: No se pudo cargar método "Obtener condominios por usuario"');
            }
        });
    }

    function GrabarLibro() {

        var condominio = $('select#selectCondominio').val();
        var cuerpo = $("#cuerpo").val();
        var usuario = $("#lb_nombreu").val();
        var perfil = $("#lb_perfil").val(); 

        if (cuerpo.length < 10)
        {
            Alert.render('Debe agregar un cuerpo de al menos 10 caracteres');
        } else
        {
            if (condominio == "") {
                Alert.render('Debe seleccionar un condominio de residencia');
            } else {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GrabarLibro", "Anuncios")',
                    content: "application/json; charset=utf-8",
                    dataType: "json",
                    data: { "Condominio": condominio,"Perfil":perfil,"Persona":usuario,"Cuerpo":cuerpo },
                    success: function (respuesta) {
                        if (respuesta.model != "") {
                            Alert.render('Libro actualizado correctamente');
                            $("#cuerpo").val("");  
                        } else {
                            Alert.render('No se han conseguido grabar el registro');
                        }
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        Alert.render('Error: No se pudo cargar método "Grabar Libro"');
                    }
                });
            }
        }
        
    }

</script>